# fly.toml app configuration file generated for fdla-event-manager on 2023-10-15T14:44:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fdla-event-manager"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "3000"
  APP_URL = "https://fdla-event-manager.fly.dev"
  DATABASE_ENVIRONMENT = "production"
